name: todo_redesign
description: "A new Flutter project."
publish_to: 'none'
version: 0.1.0

environment:
  sdk: ^3.7.0

dependencies:
  file_picker: ^9.2.1
  flutter:
    sdk: flutter
  flutter_localizations:
    sdk: flutter
  flutter_quill: ^11.1.0
  flutter_quill_extensions: ^11.0.0
  intl: ^0.20.2
  path: ^1.9.1
  path_provider: ^2.1.5
  permission_handler: ^11.4.0
  provider: ^6.1.2
  shared_preferences: ^2.5.2

dependency_overrides:
  intl: ^0.19.0



dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^5.0.0
  rename_app: ^1.6.2

flutter:
  uses-material-design: true
  assets:
    - assets/
